### ISSUE TITLE
Missing required package `request`

### ISSUE THREAD

**Issue by gatapia** [pouriaa/bitbucket-to-github#1]
doing an `npm i` and then `node index.js` fails with the error `Error: Cannot find module 'request'`.

Doing an `npm i request` fixes this.

Please add request to the dependencies.  Sorry no pull request, not at dev machine at the moment.

PS: cool little repo, was about to write my own script, saved me the work.

**Comment by pouriaa** [comment]
Thanks for the feedback. I went ahead and added in the the dependency on this [commit.](https://github.com/pouriaa/bitbucket-to-github/commit/795d8fa966282711a9861f06718b188770fe0009)
